### PR TITLE
Code formatted as per PEP8, Function block for getting credentials removed

### PR DESCRIPTION
**Pull request by pravarag**
I can see that an extra code block as "get_credentials()" has been used in the '__main__().py' program. So I was wondering, is there any plan to utilise those credentials or the function somewhere else like in any other script or so? If not, then I've tested the program by removing it and adding few lines in the main function itself, checking for credentials. Also, as part of this PR, I've tried to remove few PEP-8 errors.

### CODE REVIEW

**Comment by TarmacDenter** [comment]
I abstracted it specifically to be testable and to allow for try/catch handling if someone wanted to add an additional credentials store down the line like from a yaml file or something. There’s no reason to make it untestable and less modular. `main()` functions shouldn’t handle credentials on their own.

**Comment by pravarag** [comment]
Reading the credentials for a Spotify account sounds strange, but if you have tested then it's good. But , I can still see that line 140, line 141 as an extra. When, we can pass the username directly to Spotify class. Plus, there were some lines changed as per PEP-8 format as well. Have you thought about adding PEP-8 based linting?

**Comment by TarmacDenter** [comment]
Not my repo, so I don’t PEP8 other people’s code as it litters the commits. Those should be their own atomic PR’s from ones that change any actual code. So it’s up to him. I’m rewriting the whole thing in my own to be extendable with different lyrics services and global/user configurations so I haven’t worked on this in a long time. I just popped in to explain why I made the credentials it’s own function.

**Comment by TarmacDenter** [comment]
Also, the credentials namedtuple was added for readability. You could simply *unpack the return value of `get_credentials()` it into two variables if you wanted to keep it to one line. But it’s usually preferable to add a clean line instead of escaping a line break if you can help it.

**Pull request merged**
